FROM node:18-alpine

WORKDIR /app

# Installer json-server globalement
RUN npm install -g json-server

# Copier le fichier db.json
COPY db.json /app/db.json

# Exposer le port 3000
EXPOSE 3000

# Lancer json-server
CMD ["json-server", "--host", "0.0.0.0", "--port", "3000", "--watch", "db.json"]
